### ISSUE TITLE
menu wont open

### ISSUE THREAD

**Issue by FijiAura** [Pololak/PolzHax#2]

**Comment by Pololak** [comment]
DM me in discord: pololak

**Comment by FijiAura** [comment]
i dont have discord

**Comment by Pololak** [comment]
Check adaf-dll folder if it has PolzHax.dll

**Comment by FijiAura** [comment]
it has but still not opening

**Comment by Pololak** [comment]
Do you have Cheat Engine?

**Comment by FijiAura** [comment]
no

**Comment by Pololak** [comment]
Which GD version are you using, or on which GDPS you trying this?

**Comment by FijiAura** [comment]
1.9, platinum gdps

**Comment by Pololak** [comment]
Did you extract everything from archive to GDPS folder (where .exe is located)

**Comment by FijiAura** [comment]
yes

**Comment by Pololak** [comment]
Well, idk what's the problem, maybe you pressing wrong keybind to open it, idk. Also download discord and i guess some members from Platinum will help you.

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by ViridiSt** [comment]
where the hell is the adaf.h!l folder, I cant find it
